(ns binance-clj.spot.endpoints
  "Declarative registry entries for Phase 5-6 Spot REST endpoints."
  (:require [binance-clj.spot.normalize :as normalize]
            [binance-clj.spot.signed-normalize :as signed-normalize]
            [binance-clj.spot.signed-validation :as signed-validation]
            [binance-clj.spot.validation :as validation]))

(def specs
  "Official Public Spot REST endpoint specifications shipped by default."
  [{:id :spot/ping
    :method :get
    :path "/api/v3/ping"
    :security :none
    :execution :read
    :weight 1
    :validate validation/no-params
    :parser normalize/ping}
   {:id :spot/server-time
    :method :get
    :path "/api/v3/time"
    :security :none
    :execution :read
    :weight 1
    :validate validation/no-params
    :parser normalize/server-time}
   {:id :spot/exchange-info
    :method :get
    :path "/api/v3/exchangeInfo"
    :security :none
    :execution :read
    :weight 20
    :validate validation/exchange-info
    :parser normalize/exchange-info}
   {:id :spot/ticker-price
    :method :get
    :path "/api/v3/ticker/price"
    :security :none
    :execution :read
    :weight 0
    :validate validation/ticker-price-or-book
    :parser normalize/ticker-price}
   {:id :spot/ticker-24h
    :method :get
    :path "/api/v3/ticker/24hr"
    :security :none
    :execution :read
    :weight 0
    :validate validation/ticker-24h
    :parser normalize/ticker-24h}
   {:id :spot/book-ticker
    :method :get
    :path "/api/v3/ticker/bookTicker"
    :security :none
    :execution :read
    :weight 0
    :validate validation/ticker-price-or-book
    :parser normalize/book-ticker}
   {:id :spot/depth
    :method :get
    :path "/api/v3/depth"
    :security :none
    :execution :read
    :weight 0
    :validate validation/depth
    :parser normalize/depth}
   {:id :spot/account
    :method :get
    :path "/api/v3/account"
    :security :signed
    :permission :user-data
    :execution :read
    :weight 20
    :validate signed-validation/account
    :parser signed-normalize/account}
   {:id :spot/my-trades
    :method :get
    :path "/api/v3/myTrades"
    :security :signed
    :permission :user-data
    :execution :read
    :weight 0
    :validate signed-validation/my-trades
    :parser signed-normalize/my-trades}
   {:id :spot/test-order
    :method :post
    :path "/api/v3/order/test"
    :security :signed
    :permission :trade
    :execution :read
    :retry-policy :never
    :weight 0
    :validate signed-validation/test-order
    :parser signed-normalize/test-order}
   {:id :spot/new-order
    :method :post
    :path "/api/v3/order"
    :security :signed
    :permission :trade
    :execution :command
    :weight 1
    :validate signed-validation/new-order
    :parser signed-normalize/new-order}
   {:id :spot/query-order
    :method :get
    :path "/api/v3/order"
    :security :signed
    :permission :user-data
    :execution :read
    :weight 4
    :validate signed-validation/query-order
    :parser signed-normalize/query-order}
   {:id :spot/cancel-order
    :method :delete
    :path "/api/v3/order"
    :security :signed
    :permission :trade
    :execution :command
    :weight 1
    :validate signed-validation/cancel-order
    :parser signed-normalize/cancel-order}
   {:id :spot/open-orders
    :method :get
    :path "/api/v3/openOrders"
    :security :signed
    :permission :user-data
    :execution :read
    :weight 0
    :validate signed-validation/open-orders
    :parser signed-normalize/open-orders}])
